#!/bash/bin
#the first argument to be the variable
FILENAME="$1"

#check if variable is empty
if  [[ -z "$FILENAME" ]] ; then
  echo "please provide a name for your file as the argument"
exit 1 
fi
chmod u+x "$FILENAME"


